keys:
  - &admin_sincore age10rvdume3yfwjxu2wc64dmkmc06qsm7fe0fvrpqt8mdrdksqx75vspwns56
  - &server_sushi age10e6ptnwuy76r2rx7cncp5gvh06eghvdungnhrkkea8t32caxjdxshwcy83
creation_rules:
  - path_regex: secrets/default.yaml$
    key_groups:
      - age:
          - *admin_sincore
          - *server_sushi
  - path_regex: secrets/tailscale/default.yaml$
    key_groups:
      - age:
          - *admin_sincore
          - *server_sushi
  - path_regex: secrets/networking/default.yaml$
    key_groups:
      - age:
          - *admin_sincore
          - *server_sushi
