[formatter.alejandra]
command = "alejandra"
excludes = []
includes = ["*.nix"]
options = []

[formatter.deadnix]
command = "deadnix"
excludes = []
includes = ["*.nix"]
options = ["--edit"]

[formatter.statix]
command = "sh"
excludes = []
includes = ["*.nix"]
options = ["-eucx", """
for file in "''$@"; do
statix fix "$file"
done
	""", "--"]

[formatter.mdformat]
command = "mdformat"
excludes = []
includes = ["*.md"]
options = []

[formatter.taplo]
command = "taplo"
excludes = []
includes = ["*.toml"]
options = ["format"]

[formatter.shfmt]
command = "shfmt"
excludes = []
includes = ["*.sh"]
options = ["-i", "2", "-s", "-w"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
]
