name: Sync Fork with Upstream and Create PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create temporary branch for PR
        run: |
          git checkout -b temp-pr-branch

      - name: Fetch original
        run: |
          git remote add upstream https://github.com/Spacebar-Cowboys/nyx.git
          git fetch upstream

      - name: Merge changes excluding specific directories
        run: |
          git checkout main
          git restore --source upstream/main --staged --worktree -- .
          git reset HEAD systems/x86_64-linux/ homes/
          git checkout HEAD systems/x86_64-linux/ homes/

      - name: Commit changes
        run: |
          git add .
          git commit -m "Syncing changes with upstream excluding specific directories" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: |
          git push --set-upstream origin temp-pr-branch

      - name: Create or Update Pull Request
        run: |
          function gh_pr_up() {
            gh pr create "$@" || gh pr edit "$@"
          }
          gh_pr_up --title "Update from upstream" \
                   --body "Merged changes from the original repository excluding 'systems/x86_64-linux' and 'homes' directories." \
                   --head use-the-fork:temp-pr-branch \
                   --base main \
                   --repo Spacebar-Cowboys/nyx
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
